<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CsvToOfx.Core\CsvToOfx.Core.csproj" />
    <ProjectReference Include="..\CsvToOfx.Parsers\CsvToOfx.Parsers.csproj" />
    <ProjectReference Include="..\CsvToOfx.Writers.Ofx\CsvToOfx.Writers.Ofx.csproj" />
    <ProjectReference Include="..\CsvToOfx.Writers.Qif\CsvToOfx.Writers.Qif.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
  </ItemGroup>
    
    <ItemGroup>
        <EmbeddedResource Include="Resources\SecurityMap.csv" />
    </ItemGroup>


  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

</Project>
